gqa/gqa/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('gqaMapper.urls', namespace='gqaMapper')),
    path('admin/', admin.site.urls),
]

gqa/gqaMapper/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login

app_name = 'qgaMapper'
urlpatterns = [
    path("", views.index, name = "index"),
    path("search", views.search, name = "search"), #Homepage->Search
    path("help", views.help, name = "help"), #Homepage->Help
]

gqa/gqaMapper/models.py
from django.db import models

# Create your models here.

gqa/gqaMapper/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'gqaMapper/index.html')

def search(request):
    return render(request, 'gqaMapper/search.html')

def help(request):
    return render(request, 'gqaMapper/help.html')

gqa/gqaMapper/templates/gqaMapper/components/javascript.html
<script
  src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
  crossorigin="anonymous"
></script>
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
  integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
  crossorigin="anonymous"
></script>
<script
  src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
  integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
  crossorigin="anonymous"
></script>
<!-- DataTables (bootstrap 4 version) for table sorting -->
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

gqa/gqaMapper/templates/gqaMapper/components/navbar.html
<nav id="navbar-wrapper" class="navbar bg-dark navbar-expand" style="padding:0em">
    <div class="container">
        <h3 class="">
            <a href="{% url "gqaMapper:index" %}">
                <span class="title font-weight-bold" style=" font: 0.7em sans-serif; color: whitesmoke;">
                    <b>G-Quad-Virus</b>
                </span>
                <span class="description font-italic font-weight-light" style=" font: 0.6em sans-serif; color: whitesmoke;">A tool for analysing G-Quadruplex sequence in Human Virses</span>
            </a>
        </h3>
        <ul>
            <li>
                <a href="{% url "gqaMapper:index" %}" class="" target="_self">Home</a>
            </li>
            <li>
                <a href="{% url "gqaMapper:search" %}" class="" target="_self">Search</a>
            </li>
            <li>
                <a href="{% url "gqaMapper:help" %}" class="" target="_self">Help</a>
            </li>
        </ul>
    </div>
</nav>

gqa/gqaMapper/templates/gqaMapper/components/stylesheets.html
{% load static %}
<link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
  crossorigin="anonymous"
/>
<link rel="stylesheet" href="{% static 'gqaMapper/css/layout.css' %}" />

gqa/gqaMapper/templates/gqaMapper/help.html
{% extends "gqaMapper/index.html" %} {% block body %}

<center>
  <h1>Help</h1>
  <hr style="border: none; border-bottom: 1px solid black;" />
  <p>
    This page would soon provide guidance to user as how to perform the sequence
    analysis.
  </p>
</center>
{% endblock %}

gqa/gqaMapper/templates/gqaMapper/index.html
{% extends "gqaMapper/layout.html" %} {% load static %} {% block body %} &nbsp;
<!-- <h1>Home</h1> -->
<div class="row">
  <div class="col-lg-12">
    <div class="row">
      <div class="col-lg">
        <span>
          <p style="font-size: 1.5em">
            Welcome to <strong>G-Quad Virus</strong>!
          </p>
          <hr style="border: none; border-bottom: 1px solid black;" />
          <p>The best place for performing analysis</p>
        </span>
      </div>
    </div>
  </div>
</div>

{% endblock %} {% block javascript %} {% endblock %}

gqa/gqaMapper/templates/gqaMapper/layout.html
{% load static %} <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{ title }}</title>

    {% include 'gqaMapper/components/stylesheets.html' %}
    <!-- include any other custom style blocks -->
    {% block style %}{% endblock %}
  </head>

  <body>
    {% include 'gqaMapper/components/navbar.html' %}

    <div class="container">{% block body %}{% endblock %}</div>

    {% include 'gqaMapper/components/javascript.html' %}

    <!-- include any other javascript blocks -->
    {% block javascript %}{% endblock %}
  </body>
</html>

gqa/gqaMapper/templates/gqaMapper/search.html
{% extends "gqaMapper/index.html" %} {% block body %} &nbsp;
<div class="row">
  <div class="col-lg">
    <h1 align="center">Search</h1>
    <hr style="border: none; border-bottom: 1px solid black;" />
  </div>
</div>
&nbsp;
<div class="row">
  <div class="col-md-12">
    &nbsp;
    <div class="tab-content" id="nav-tabContent">
      <div
        class="tab-pane fade show active"
        id="nav-1"
        role="tabpanel"
        aria-labelledby="nav-1-tab"
      >
        <form>
          <div class="form-group">
            <label for="exampleFormControlTextarea1"
              >Please input your sequence</label
            >
            <textarea
              class="form-control"
              id="exampleFormControlTextarea1"
              rows="15"
            ></textarea>
          </div>
          <button
            type="submit"
            class="btn badge-dark"
            style="width:20vw; float: right;"
          >
            Submit
          </button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}